[workspace]

[package]
name = "ethercat"
description = "Binding to the Etherlab open-source EtherCAT master"
keywords = ["ethercat", "master", "etherlab"]
version = "0.1.3"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
libc = "0.2.49"
memmap = "0.7.0"
derive-new = "0.5.6"
ethercat-sys = { path = "ethercat-sys", version = "0.1.3" }
