[workspace]

[package]
name = "ethercat-testplc"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
ethercat = { path = "ethercat" }
ethercat-plc = { path = "ethercat-plc" }
ethercat-xml = { path = "ethercat-xml" }
ethercat-derive = { path = "ethercat-derive" }
