[workspace]

[package]
name = "ethercat-plc"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[dependencies]
log = "*"
libc = "*"
time = "*"
mlzlog = "*"
byteorder = "*"
crossbeam-channel = "*"
ethercat = { path = "ethercat" }
ethercat-derive = { path = "ethercat-derive" }
