[package]
name = "ethercat"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[dependencies]
libc = "0.2.46"
memmap = "0.7.0"
derive-new = "0.5.6"
ethercat-sys = { path = "../ethercat-sys" }
