[package]
name = "ethercat"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[dependencies]
libc = "0.2"
memmap = "0.7"
ethercat-sys = { path = "../ethercat-sys" }
